# Copyright (C) 2015 The CyanogenMod Project
# Copyright (C) 2015 The Android Open Kang Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/zerofltespr/setup-makefiles.sh

## zerofltespr/device-proprietary-blobs.txt
PRODUCT_COPY_FILES += \
	vendor/samsung/zerofltespr/proprietary/lib/lib_DNSe_NRSS_ver226.so:system/lib/lib_DNSe_NRSS_ver226.so \
	vendor/samsung/zerofltespr/proprietary/lib/lib_SamsungRec_V04012_WNR003.so:system/lib/lib_SamsungRec_V04012_WNR003.so \
	vendor/samsung/zerofltespr/proprietary/vendor/firmware/bcm4358A3_V0036.0054.hcd:system/vendor/firmware/bcm4358A3_V0036.0054.hcd \
	vendor/samsung/zerofltespr/proprietary/app/mcRegistry/ffffffff000000000000000000000028.tlbin:system/app/mcRegistry/ffffffff000000000000000000000028.tlbin \
	vendor/samsung/zerofltespr/proprietary/app/mcRegistry/ffffffff00000000000000000000002a.tlbin:system/app/mcRegistry/ffffffff00000000000000000000002a.tlbin \
	vendor/samsung/zerofltespr/proprietary/lib/libril.so:system/lib/libril.so \
	vendor/samsung/zerofltespr/proprietary/lib/librilutils.so:system/lib/librilutils.so \
	vendor/samsung/zerofltespr/proprietary/lib64/libril.so:system/lib64/libril.so \
	vendor/samsung/zerofltespr/proprietary/lib64/librilswitch.so:system/lib64/librilswitch.so \
	vendor/samsung/zerofltespr/proprietary/lib64/librilutils.so:system/lib64/librilutils.so \
	vendor/samsung/zerofltespr/proprietary/vendor/firmware/setfile_2p2.bin:system/vendor/firmware/setfile_2p2.bin
